import { Intent } from "./types.js";
//All generated by an AI model to create varied and natural-sounding responses
/**
 * Response templates for each intent
 * Contains multiple response variations to make the chatbot feel more natural
 */
export const BotResponses: Record<Intent, string[]> = {
    [Intent.Greeting]: [
        "Hello! How can I help you today?",
        "Hi there! What can I do for you?",
        "Hey! Nice to see you. How can I assist?",
        "Good day! What brings you here?",
        "Greetings! I'm here to help.",
        "Hello! Welcome! What would you like to know?",
        "Hi! Ready to assist you with anything you need.",
        "Hey there! What's on your mind?",
        "Good to see you! How may I be of service?",
        "Hello friend! What can I help you with today?",
        "Hi! I'm all ears. What do you need?",
        "Welcome back! How can I assist you?",
        "Hey! What would you like to talk about?",
        "Hi there! I'm here whenever you need me.",
        "Hello! Feel free to ask me anything!",
    ],

    [Intent.Goodbye]: [
        "Goodbye! Have a great day!",
        "See you later! Take care!",
        "Bye! Come back anytime!",
        "Farewell! It was nice chatting with you.",
        "See you soon! Stay safe!",
        "Goodbye! Feel free to return whenever you need help.",
        "Take care! Have a wonderful day ahead!",
        "Bye for now! Hope to chat again soon.",
        "Until next time! Best wishes!",
        "Goodbye! Don't hesitate to come back if you need anything.",
        "See you! Have an amazing rest of your day!",
        "Bye! Thanks for chatting with me!",
        "Catch you later! Be well!",
        "Farewell! It's been a pleasure helping you.",
        "Good night! Sleep well and see you next time!",
    ],

    [Intent.Help]: [
        "I'm here to help! What do you need assistance with?",
        "Of course! Tell me what you're having trouble with.",
        "I'd be happy to help! What's the issue?",
        "No problem! What can I help you figure out?",
        "Let me assist you! What do you need help with?",
        "I'm here for you! What seems to be the problem?",
        "Happy to help! What's troubling you?",
        "Sure thing! What do you need guidance on?",
        "I'm ready to assist! What's confusing you?",
        "Let me guide you through this! What do you need?",
        "Don't worry, I'm here to help! What's going on?",
        "I'll do my best to assist! What can I help with?",
        "Tell me what you need and I'll help you out!",
        "I'm all yours! What assistance do you require?",
        "Let's solve this together! What do you need help with?",
        "I'm here to support you! What's the challenge?",
        "Count on me! What would you like assistance with?",
    ],

    [Intent.Query]: [
        "That's an interesting question! Let me help you with that.",
        "Great question! Here's what I know...",
        "I'd be happy to explain that to you!",
        "Let me provide you with some information on that.",
        "Good inquiry! Here's what I can tell you...",
        "I can help clarify that for you!",
        "That's something I can explain! Let me break it down.",
        "Interesting topic! Here's the information you're looking for...",
        "I have some insights on that! Let me share them with you.",
        "Let me give you the details you need!",
        "I can answer that! Here's what you should know...",
        "That's a valid question! Allow me to explain.",
        "I understand what you're asking. Here's the answer...",
        "Let me provide some clarity on that topic!",
        "Good thinking! Here's the information...",
        "I can shed some light on that for you!",
        "Let me explain that in detail for you!",
    ],

    [Intent.Smalltalk]: [
        "I'm doing great, thank you for asking! How about you?",
        "I'm just a chatbot, but I'm always happy to chat!",
        "I'm here and ready to talk! What's on your mind?",
        "Doing well! Thanks for the friendly chat!",
        "I'm functioning perfectly! How are you doing today?",
        "I'm good! Always happy to have a conversation with you.",
        "I'm a bot, so I don't have feelings, but I appreciate the chat!",
        "I'm doing fantastic! It's nice to chat with you!",
        "All systems operational! How's your day going?",
        "I'm great! Thanks for making conversation with me!",
        "I exist to chat with awesome people like you!",
        "I'm an AI assistant, always here for a friendly conversation!",
        "Doing well! I enjoy our little chats!",
        "I'm programmed to be helpful and friendly, and I love it!",
        "I'm good! What about you? How's everything?",
        "I may be artificial, but I genuinely enjoy talking with you!",
        "I'm here and happy! What would you like to chat about?",
    ],

    [Intent.Weather]: [
        "I don't have real-time weather data, but you can check a weather app!",
        "For current weather information, I recommend checking weather.com or your local forecast.",
        "I can't access live weather data, but try asking a weather service!",
        "Unfortunately, I don't have weather capabilities right now. Try a weather app!",
        "I'd love to tell you the weather, but I don't have that info. Check your weather app!",
        "For accurate weather forecasts, I suggest using a dedicated weather service.",
        "I don't have access to weather data, but Google or a weather app can help!",
        "Weather info isn't my specialty, but there are great weather apps out there!",
        "I can't check the weather for you, but your phone's weather app can!",
        "For the latest weather updates, please consult a weather website or app.",
        "I wish I could tell you the weather! Try checking weather.gov or similar sites.",
        "Weather forecasting isn't in my current capabilities. Try AccuWeather or Weather.com!",
        "I don't have live weather feeds, but I recommend checking a reliable weather source!",
        "For weather conditions, your best bet is a dedicated weather application.",
        "I can't provide weather information, but Siri, Alexa, or Google can help!",
    ],

    [Intent.Search]: [
        "I can't perform web searches, but I can help with information I know!",
        "For web searches, try using Google, Bing, or your favorite search engine!",
        "I don't have search capabilities, but what specific information do you need?",
        "I can't browse the web, but I'm happy to answer questions within my knowledge!",
        "For searching online, use a search engine. I can help with what I know!",
        "I'm not connected to search engines, but tell me what you're looking for!",
        "Web searching isn't my function, but I can provide information I have!",
        "I can't search the internet, but maybe I can still help with your question!",
        "For online searches, use Google or another search engine. What do you need to know?",
        "I don't have browsing capabilities, but ask me directly and I'll try to help!",
        "Searching the web isn't something I can do, but I might have the answer already!",
        "I can't look things up online, but I have plenty of knowledge to share!",
        "Try a search engine for web searches. I'm here for direct questions!",
        "I'm not a search engine, but I can answer many questions directly!",
        "For web searches, Google is your friend! For questions, I'm here to help!",
    ],

    [Intent.Gratitude]: [
        "You're welcome! Happy to help!",
        "My pleasure! Anytime!",
        "Glad I could assist you!",
        "No problem at all! That's what I'm here for!",
        "You're very welcome! Feel free to ask anytime!",
        "Happy to be of service!",
        "It's my pleasure to help you!",
        "Anytime! I'm here whenever you need me!",
        "You're welcome! Don't hesitate to reach out again!",
        "Glad to help! That's what I do best!",
        "No worries! I enjoy helping you!",
        "You're most welcome! Come back anytime!",
        "Always happy to assist! You're welcome!",
        "My pleasure! I'm glad I could make things easier for you!",
        "You're welcome! Thanks for being so polite!",
        "Happy to help out! That's what friends are for!",
        "Absolutely! Glad everything worked out!",
    ],

    [Intent.Affirmative]: [
        "Great! Let's proceed with that.",
        "Excellent! I'll take care of it right away.",
        "Perfect! I'll get that done for you.",
        "Understood! Moving forward now.",
        "Sounds good! I'm on it!",
        "Alright! Consider it done!",
        "Fantastic! I'll handle that for you.",
        "Got it! Processing your request now.",
        "Wonderful! I'll make that happen.",
        "Confirmed! I'll proceed with your request.",
        "Okay! I'll get started on that immediately.",
        "Absolutely! I'll take care of it.",
        "Sure thing! Let me do that for you.",
        "Roger that! I'm working on it now.",
        "You got it! I'll make it happen.",
        "Affirmative! Your wish is my command!",
        "All set! I'll execute that right away.",
    ],

    [Intent.Negative]: [
        "No problem! Let me know if you change your mind.",
        "Understood! I won't proceed with that.",
        "Alright, I'll cancel that request.",
        "Got it! Nothing will be done then.",
        "Okay, I'll skip that. Anything else I can help with?",
        "Fair enough! Let me know what you'd prefer instead.",
        "No worries! I'll hold off on that.",
        "Understood! Request cancelled. What else can I do?",
        "Okay, I won't do that. Is there something else?",
        "Got it! Stopping that action now.",
        "Alright, I'll abort that process.",
        "Understood! Let me know if you need anything else.",
        "No problem at all! What would you like to do instead?",
        "Okay, I'll disregard that. How else can I help?",
        "Got it! I'll leave that alone then.",
        "Understood! Feel free to ask for something different.",
        "Alright, request withdrawn. What can I do for you?",
    ],

    [Intent.Unknown]: [
        "I'm not quite sure what you mean. Could you rephrase that?",
        "I didn't quite understand. Can you ask in a different way?",
        "Hmm, I'm not sure about that. Could you clarify?",
        "I'm having trouble understanding. Can you provide more details?",
        "That's not something I recognize. Can you elaborate?",
        "I'm not following. Could you explain that differently?",
        "I'm not sure how to help with that. Can you be more specific?",
        "I didn't catch that. Mind rephrasing your question?",
        "That's unclear to me. Could you give me more context?",
        "I'm not certain what you're asking. Can you try again?",
        "I don't quite understand. Could you explain further?",
        "That's a bit confusing to me. Can you clarify your request?",
        "I'm not sure I got that. Could you say it another way?",
        "I'm drawing a blank here. Can you provide more information?",
        "That doesn't ring a bell. Could you be more specific?",
        "I'm having difficulty understanding that. Can you help me out?",
        "I'm not quite picking up what you're putting down. Can you rephrase?",
    ],
};

/**
 * Get a random response for a given intent
 * @param intent The intent to get a response for
 * @returns A random response string for that intent
 */
export function getRandomResponse(intent: Intent): string {
    const responses = BotResponses[intent];
    if (!responses || responses.length === 0) {
        return "I'm not sure how to respond to that.";
    }
    const randomIndex = Math.floor(Math.random() * responses.length);
    return responses[randomIndex]!;
}

/**
 * Get multiple random responses for an intent (useful for variety)
 * @param intent The intent to get responses for
 * @param count Number of unique responses to get
 * @returns Array of random unique response strings
 */
export function getMultipleResponses(intent: Intent, count: number): string[] {
    const responses = BotResponses[intent];
    if (!responses || responses.length === 0) {
        return ["I'm not sure how to respond to that."];
    }

    // Shuffle and take the first 'count' items
    const shuffled = [...responses].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(count, shuffled.length));
}
